// Generated by IB v0.7.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation AmbientLightNode
@end

@implementation BallNode
@end

@implementation CameraNode
@end

@implementation TDScene
@end

@implementation GameScene
@end

@implementation ViewController
@end

